// <auto-generated />
using Aeropuerto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aeropuerto.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20190724102513_Aeropuerto.AddCuidaoAviones")]
    partial class AeropuertoAddCuidaoAviones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aeropuerto.Avion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autonomia");

                    b.Property<string>("Modelo");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("CuidaoAviones");
                });

            modelBuilder.Entity("Aeropuerto.Piloto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<string>("Nombre");

                    b.Property<double>("Sueldo");

                    b.HasKey("ID");

                    b.ToTable("Pilotos");
                });
#pragma warning restore 612, 618
        }
    }
}
